export const USER_TYPE_ID_MAPPING = {
  REVIEWER: 1,
  APPROVER: 2,
  INITIATOR: 3,
};

export const PARTNER_TYPE_MAPPING = {
  PROPRIETOR: 1,
  PRIVATE_LIMITED: 2,
};

export const PROJECT_TYPE_MAPPING = {
  Railway: 1,
  'Earth work': 2,
  Building: 3,
  Road: 4,
  Pipeline: 5,
};

export const PARTNER_TYPES = ['PROPRIETOR', 'PRIVATE_LIMITED'];

export const STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const PROJECT_TYPES = [
  'Railway',
  'Earth work',
  'Building',
  'Road',
  'Pipeline',
];

export const EXPENSE_CODES = [
  'OBB-100	Opening Bank Statement Balance',
  'CCC-100	Collection from Customer',
  'CTC-110	Cash Transfer Control',
  'BTC-110	Bank Transfer Control',
  'CIO-120	Income from Others (FD / EMD / Retention/ IT Refund)',
  'CIP-130	Investment from Promoters',
  'ESW-200	Salaries / Wages',
  'EIR-210	Imprest / Reimbursement',
  'EME-220	Misc Expense',
  'EBP-230	Business Promotion',
  'EPA-240	Employee Project Advance',
  'EWM-250	Employee Welfare / Meal',
  'LLT-300	Long Term Loan',
  'LVL-310	Vehicle Loan',
  'LPL-320	Property Loan',
  'LIP-330	Interest Paid',
  'LBC-340	Bank Charges',
  'LCC-350	Credit Card Payment',
  'ESI-400	Employees State Insurance (ESI)',
  'EPO-410	Employees Provident Fund (PF)',
  'GST-420	Goods and Services Tax (GST)',
  'TDS-430	Tax Deducted at Source (TDS)',
  'LWF-440	Labour Welfare Fund (LWF)',
  'PPP-500	Partner Payment',
  'PBP-510	Borrow Payment',
  'PPF-520	Professional Fees',
  'PSI-530	Annual Subscription / Insurance',
  'PCE-550	Computer Equipment',
  'POE-560	Office Equipment',
  'PPM-570	Plant & Machinery',
  'PCS-580	Courier Services',
  'PPS-590	Printing & Stationary',
  'PFP-600	Fuel / Petro Card Payment',
  'PRM-610	Repair & Maintenance',
  'RRT-620	Registration Charges / Road Tax',
  'PTE-630	Tools & Equipment',
  'RRP-700	Return to Promoters',
  'RGR-800	Office / Guest House Rent',
  'RGM-810	Office / Guest House Maintenance',
  'REB-820	Office / Guest House Electricity Bill',
  'RIP-830	Internet Service Provider',
  'RMT-840	Mobile / Telephone',
  'RPM-850	Plant & Machinery Rental',
  'OTF-900	Online Proceesing / Tender  Fees',
  'EMD-910	Earnest Money Deposit',
  'EFD-920	Earnest Fixed Deposit',
];

export const EXPENSE_CODES_MAPPING = {
  'OBB-100	Opening Bank Statement Balance': 1,
  'CCC-100	Collection from Customer': 2,
  'CTC-110	Cash Transfer Control': 3,
  'BTC-110	Bank Transfer Control': 4,
  'CIO-120	Income from Others (FD / EMD / Retention/ IT Refund)': 5,
  'CIP-130	Investment from Promoters': 6,
  'ESW-200	Salaries / Wages': 7,
  'EIR-210	Imprest / Reimbursement': 8,
  'EME-220	Misc Expense': 9,
  'EBP-230	Business Promotion': 10,
  'EPA-240	Employee Project Advance': 11,
  'EWM-250	Employee Welfare / Meal': 12,
  'LLT-300	Long Term Loan': 13,
  'LVL-310	Vehicle Loan': 14,
  'LPL-320	Property Loan': 15,
  'LIP-330	Interest Paid': 16,
  'LBC-340	Bank Charges': 17,
  'LCC-350	Credit Card Payment': 18,
  'ESI-400	Employees State Insurance (ESI)': 19,
  'EPO-410	Employees Provident Fund (PF)': 20,
  'GST-420	Goods and Services Tax (GST)': 21,
  'TDS-430	Tax Deducted at Source (TDS)': 22,
  'LWF-440	Labour Welfare Fund (LWF)': 23,
  'PPP-500	Partner Payment': 24,
  'PBP-510	Borrow Payment': 25,
  'PPF-520	Professional Fees': 26,
  'PSI-530	Annual Subscription / Insurance': 27,
  'PCE-550	Computer Equipment': 28,
  'POE-560	Office Equipment': 29,
  'PPM-570	Plant & Machinery': 30,
  'PCS-580	Courier Services': 31,
  'PPS-590	Printing & Stationary': 32,
  'PFP-600	Fuel / Petro Card Payment': 33,
  'PRM-610	Repair & Maintenance': 34,
  'RRT-620	Registration Charges / Road Tax': 35,
  'PTE-630	Tools & Equipment': 36,
  'RRP-700	Return to Promoters': 37,
  'RGR-800	Office / Guest House Rent': 38,
  'RGM-810	Office / Guest House Maintenance': 39,
  'REB-820	Office / Guest House Electricity Bill': 40,
  'RIP-830	Internet Service Provider': 41,
  'RMT-840	Mobile / Telephone': 42,
  'RPM-850	Plant & Machinery Rental': 43,
  'OTF-900	Online Proceesing / Tender  Fees': 44,
  'EMD-910	Earnest Money Deposit': 45,
  'EFD-920	Earnest Fixed Deposit': 46,
};

export const EXPENSE_INTERVAL_TYPES = ['ACTUAL', 'RECURRING', 'ONE_TIME'];
