export const USER_TYPE_ID_MAPPING = {
  REVIEWER: 1,
  APPROVER: 2,
  INITIATOR: 3,
};

export const PARTNER_TYPE_MAPPING = {
  PROPRIETOR: 1,
  PRIVATE_LIMITED: 2,
};

export const PROJECT_TYPE_MAPPING = {
  Railway: 1,
  'Earth work': 2,
  Building: 3,
  Road: 4,
  'Rural Water Supply': 5,
};

export const PARTNER_TYPES = ['PROPRIETOR', 'PRIVATE_LIMITED'];

export const STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jammu and Kashmir',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli',
  'Daman and Diu',
  'Delhi',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

export const PROJECT_TYPES = [
  'Railway',
  'Earth work',
  'Building',
  'Road',
  'Rural Water Supply',
];

export const EXPENSE_CODES = [
  'EME-220	Misc Expense/Income',
  'PPP-500	Partner Payment W/O TDS',
  'CIO-120	Income from Others (FD / EMD / Retention/ IT Refund)',
  'OTF-900	Online Processing / Tender Fee',
  'RPM-850	Plant & Machinery Rental',
  'PBP-510	Borrow Payment',
  'RGM-810	Office / Guest House Maintenance',
  'PWT-500	Partner Payment With TDS',
  'RGR-800	Office / Guest House Rent',
  'PRM-610	Repair & Maintenance',
  'ESO-200	Salaries / Wages (Off Roll)',
  'EWM-250	Employee Welfare / Meal',
  'EBP-230	Business Promotion',
  'REB-820	Office / Guest House Electricity Bill',
  'LVL-310	Vehicle Loan',
  'RIP-830	Internet Service Provider',
  'PPS-590	Printing & Stationary',
  'PCS-580	Courier Services',
  'GST-420	Goods and Services Tax (GST)',
  'RRT-620	Registration Charges / Road Tax',
  'TDS-430	Tax Deducted at Source (TDS)',
  'EPA-240	Employee Project Advance',
  'EIR-210	Imprest / Reimbursement',
  'ESW-200	Salaries / Wages (On Roll)',
  'RMT-840	Mobile / Telephone',
  'PFP-600	Fuel / Petro Card Payment',
  'EMD-910 Earnest Money (EMD) / Security Deposit (SD)',
];

export const EXPENSE_CODES_MAPPING = {
  'EME-220	Misc Expense/Income': 1,
  'PPP-500	Partner Payment W/O TDS': 2,
  'CIO-120	Income from Others (FD / EMD / Retention/ IT Refund)': 3,
  'OTF-900	Online Processing / Tender Fee': 4,
  'RPM-850	Plant & Machinery Rental': 5,
  'PBP-510	Borrow Payment': 6,
  'RGM-810	Office / Guest House Maintenance': 7,
  'PWT-500	Partner Payment With TDS': 8,
  'RGR-800	Office / Guest House Rent': 9,
  'PRM-610	Repair & Maintenance': 10,
  'ESO-200	Salaries / Wages (Off Roll)': 11,
  'EWM-250	Employee Welfare / Meal': 12,
  'EBP-230	Business Promotion': 13,
  'REB-820	Office / Guest House Electricity Bill': 14,
  'LVL-310	Vehicle Loan': 15,
  'RIP-830	Internet Service Provider': 16,
  'PPS-590	Printing & Stationary': 17,
  'PCS-580	Courier Services': 18,
  'GST-420	Goods and Services Tax (GST)': 19,
  'RRT-620	Registration Charges / Road Tax': 20,
  'TDS-430	Tax Deducted at Source (TDS)': 21,
  'EPA-240	Employee Project Advance': 22,
  'EIR-210	Imprest / Reimbursement': 23,
  'ESW-200	Salaries / Wages (On Roll)': 24,
  'RMT-840	Mobile / Telephone': 25,
  'PFP-600	Fuel / Petro Card Payment': 26,
  'EMD-910 Earnest Money (EMD) / Security Deposit (SD)': 27,
};

export const EXPENSE_INTERVAL_TYPES = ['ACTUAL', 'RECURRING', 'ONE_TIME'];
