export const SUCCESS = 'SUCCESS';

export const FAILURE = 'FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT = 'LOGOUT';

export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';

export const REMOVE_LOGGEDIN_USER = 'REMOVE_LOGGEDIN_USER';

export const SET_USER_PERMISSIONS = 'SET_USER_PERMISSIONS';

export const SET_ALL_USERS = 'SET_ALL_USERS';

export const SET_USER_DETAILS = 'SET_USER_DETAILS';

export const SET_ALL_PARTNERS = 'SET_ALL_PARTNERS';

export const SET_PARTNER_DETAILS = 'SET_PARTNER_DETAILS';

export const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS';

export const SET_PROJECT_DETAILS = 'SET_PROJECT_DETAILS';

export const SET_ALL_EXPENSES = 'SET_ALL_EXPENSES';

export const SET_EXPENSE_DETAILS = 'SET_EXPENSE_DETAILS';

export const SET_ALL_EMPLOYEES = 'SET_ALL_EMPLOYEES';

export const SET_EMPLOYEE_DETAILS = 'SET_EMPLOYEE_DETAILS';

export const SET_ALL_PAYMENTS = 'SET_ALL_PAYMENTS';

export const SET_PAYMENT_DETAILS = 'SET_PAYMENT_DETAILS';

export const SET_ALL_REVENUES = 'SET_ALL_REVENUES';

export const SET_REVENUE_DETAILS = 'SET_REVENUE_DETAILS';
