module.exports = Object.freeze({
  GET_ALL_PROJECTS: `SELECT to_char("PR_WorkOrderDate", 'YYYY-MM-DD') as "PR_WorkOrderDateInFormat", to_char("PR_ExecutionStartDate", 'YYYY-MM-DD') as "PR_ExecutionStartDateInFormat", * FROM "Project" INNER JOIN "ProjectType" ON "ProjectType"."PRT_ID" = "Project"."PR_PRT_ID";`,
  GET_PROJECT_DETAILS: `SELECT to_char("PR_WorkOrderDate", 'YYYY-MM-DD') as "PR_WorkOrderDateInFormat", to_char("PR_ExecutionStartDate", 'YYYY-MM-DD') as "PR_ExecutionStartDateInFormat", * FROM "Project" INNER JOIN "ProjectType" ON "ProjectType"."PRT_ID" = "Project"."PR_PRT_ID" WHERE "PR_ID" = $1;`,
  ADD_NEW_PROJECT: `INSERT INTO "Project"("PR_Name", "PR_Code", "PR_Location", "PR_PRT_ID", "PR_ClientName", "PR_ConcernPersonName", "PR_ConcernPersonNumber", "PR_ConcernPersonEmail", "PR_WorkOrderNumber", "PR_WorkOrderValue", "PR_WorkOrderDate", "PR_WorkOrderValidityYear", "PR_WorkOrderValidityMonth", "PR_ExecutionStartDate", "PR_CreatedOn", "PR_CreatedBy", "PR_UpdatedBy", "PR_UpdatedOn") VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,  NOW()::DATE, $15, $15, NOW()::DATE);`,
  EDIT_A_PROJECT: `UPDATE "Project" SET "PR_Name"=$2, "PR_Code" = $3, "PR_Location" = $4, "PR_PRT_ID" = $5, "PR_ClientName" = $6, "PR_ConcernPersonName"= $7, "PR_ConcernPersonNumber"= $8, "PR_ConcernPersonEmail"= $9, "PR_WorkOrderNumber"=$10, "PR_WorkOrderValue"=$11, "PR_WorkOrderDate"= $12, "PR_WorkOrderValidityYear"= $13, "PR_WorkOrderValidityMonth"= $14, "PR_ExecutionStartDate" = $15, "PR_UpdatedBy" = $16, "PR_UpdatedOn" = NOW()::DATE WHERE "PR_ID"=$1; `,
  DELETE_A_PROJECT: `DELETE FROM "Project" WHERE "PR_ID" = $1;`,
  GET_ALL_EXPENSES_FOR_A_MONTH_OF_A_PROJECT: `SELECT "EC_Category", SUM("E_BasicValue") from "Expense" INNER JOIN "ExpenseCode" ON "ExpenseCode"."EC_ID" = "Expense"."E_EC_ID" where EXTRACT(MONTH FROM "E_ExpenseDate") = $1 AND "E_PR_ID" = $2 GROUP BY "EC_Category"`,
  GET_ALL_REVENUES_SUM_FOR_A_MONTH_OF_A_PROJECT: `SELECT SUM("R_BasicValue") from "Revenue" where "R_ProjectWorkOrderNumber" = $1 AND EXTRACT(MONTH FROM "R_ClientInvoiceDate") = $2;`,
});
